main:
  - name: Support
    identifier: support
    weight: 100
    url: https://github.com/goroedge
    params:
      header: Support community.
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Documentation
    parent: support
    url: https://rabrain.ru
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The documentation.

  - name: GitHub
    parent: support
    url: https://github.com/goroedge
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Discussion
    parent: support
    url: https://github.com/goroedge/discussions
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions and share your ideas.

  - name: Mastodon
    parent: support
    url: https://techhub.social/@goroedge
    weight: 16
    params:
      icon:
        vendor: simple
        name: mastodon
      description: Follow us on Mastodon to get latest updates.
